language: minimal

env:
  - IGNORE_PAT="^\[.*\]:"

script:
  - for f in text/*; do
      grep -vE $IGNORE_PAT $f | fold -s | diff -I $IGNORE_PAT - $f ||
        ( echo "Please wrap RFCs at 80 characters" && exit 1 );
    done
